services:
  - type: web
    name: sistema-eventos-unb
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.rxsowfuvofotbifooljx
      - key: DB_PASSWORD
        value: SistemaDB2025
      - key: DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
